import{useState,useEffect}from 'react';
import{Link,useNavigate}from 'react-router-dom';
import{useAuth}from '../context/AuthContext';
import{getUserOrders}from '../services/api';
import{Package,Clock,Truck,CheckCircle,LogOut,User,ShoppingBag,Mail,Eye,EyeOff,Crown,MapPin}from 'lucide-react';
import './AccountPage.css';
const OE='akarshsrivastava322@gmail.com';
const SI=({status})=>{if(status==='Delivered')return <CheckCircle size={16} color='#16a34a'/>;if(status==='In Transit')return <Truck size={16} color='#7c3aed'/>;if(status==='Crafting')return <Package size={16} color='#1d4ed8'/>;return <Clock size={16} color='#c2410c'/>;};
export default function AccountPage(){const{user,signIn,signUp,signOut}=useAuth();const navigate=useNavigate();const[isLogin,setIsLogin]=useState(true);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[showPwd,setShowPwd]=useState(false);const[authError,setAuthError]=useState('');const[myOrders,setMyOrders]=useState([]);const[activeTab,setActiveTab]=useState('orders');const[loading,setLoading]=useState(false);const isOwner=!!(user&&user.email&&user.email.toLowerCase()===OE.toLowerCase());useEffect(()=>{if(user)getUserOrders(user.id).then(setMyOrders).catch(console.error);},[user]);const handleAuth=async(e)=>{e.preventDefault();setAuthError('');setLoading(true);try{if(isLogin){const{error}=await signIn(email,password);if(error)throw error;}else{const{error}=await signUp(email,password);if(error)throw error;setAuthError('Check your email!');}}catch(err){setAuthError(err.message);}finally{setLoading(false);}};
const handleLogout=async()=>{await signOut();navigate('/');};
if(!user)return(<div className='account-auth-screen'><div className='auth-card glass-panel'><div className='auth-logo'>&#127800;</div><h2 className='auth-title'>{isLogin?'Welcome Back':'Join Lume'}</h2><p className='auth-subtitle'>{isLogin?'Sign in to track orders':'Create account'}</p>{authError&&<div className={authError.includes('Check')?'alert-success':'alert-error'} style={{marginBottom:'16px'}}>{authError}</div>}<form onSubmit={handleAuth} className='auth-form'><div className='auth-field'><Mail size={18}/><input type='email' placeholder='Email address' value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className='auth-field'><User size={18}/><input type={showPwd?'text':'password'} placeholder='Password' value={password} onChange={e=>setPassword(e.target.value)} required/><button type='button' onClick={()=>setShowPwd(!showPwd)} style={{background:'none',border:'none',cursor:'pointer',color:'var(--text-muted)',display:'flex'}}>{showPwd?<EyeOff size={16}/>:<Eye size={16}/>}</button></div><button type='submit' className='btn-primary w-100' disabled={loading}>{loading?'Please wait...':(isLogin?'Sign In':'Create Account')}</button></form><button className='auth-toggle' onClick={()=>{setIsLogin(!isLogin);setAuthError('');}}>{isLogin?'New here? ':'Already have an account? '}<span>{isLogin?'Create Account':'Sign In'}</span></button></div></div>);
return(<div className='account-dashboard'><div className='account-header'><div className='account-user-info'><div className='account-avatar'>{isOwner?<Crown size={22} color='#D4AF37'/>:<User size={22}/>}</div><div><h3 className='account-name'>{user.email.split('@')[0]}</h3><p className='account-email'>{user.email}</p>{isOwner&&<span className='owner-badge'>&#128081; Store Owner</span>}</div></div><div className='account-header-actions'>{isOwner&&<Link to='/admin' className='btn-primary' style={{padding:'10px 20px',fontSize:'0.85rem',display:'inline-flex',alignItems:'center',gap:'6px'}}><Crown size={14}/> Admin Panel</Link>}<button className='btn-logout' onClick={handleLogout}><LogOut size={16}/> Sign Out</button></div></div><div className='account-tabs'><button className={'account-tab'+(activeTab==='orders'?' active':'')} onClick={()=>setActiveTab('orders')}><ShoppingBag size={16}/> My Orders ({myOrders.length})</button><button className={'account-tab'+(activeTab==='profile'?' active':'')} onClick={()=>setActiveTab('profile')}><User size={16}/> Profile</button></div><div className='account-content'>{activeTab==='orders'&&(<div>{myOrders.length===0?(<div className='account-empty'><ShoppingBag size={48} color='var(--text-muted)'/><h3>No orders yet</h3><p>Your orders will appear here once placed.</p><Link to='/gallery' className='btn-primary' style={{marginTop:'8px'}}>Browse Bouquets</Link></div>):(myOrders.map(order=>(<div key={order.id} className='order-card'><div className='order-card-left'><div className='order-status-icon'><SI status={order.status}/></div><div className='order-card-info'><p className='order-item-name'>{order.item}</p><p className='order-meta'>#{order.id?order.id.slice(-8).toUpperCase():'N/A'}</p><p className='order-meta'>{order.date}</p>{order.address&&<p className='order-meta' style={{display:'flex',alignItems:'center',gap:'4px'}}><MapPin size={12}/> {order.address}</p>}</div></div><div className='order-card-right'><span className={'status-pill '+(order.status||'').toLowerCase().replace(' ','-')}>{order.status}</span><p className='order-amount'>&#8377;{Number(order.amount||0).toLocaleString('en-IN')}</p><Link to={'/track?id='+order.id} className='order-track-link'>Track Order</Link></div></div>)))}</div>)}{activeTab==='profile'&&(<div className='profile-card glass-panel'><h3 style={{marginBottom:'20px',fontFamily:'var(--font-heading)'}}>Account Details</h3><div className='profile-row'><span className='profile-label'>Email</span><span>{user.email}</span></div><div className='profile-row'><span className='profile-label'>Account Type</span><span>{isOwner?'Store Owner':'Customer'}</span></div><div style={{marginTop:'28px',paddingTop:'24px',borderTop:'1px solid #f0f0f0'}}><button className='btn-logout w-100' onClick={handleLogout} style={{justifyContent:'center'}}><LogOut size={16}/> Sign Out</button></div></div>)}</div></div>);}